Repository jenkinsci/jobcacher-plugin, pull requests merged in 2025-02, with the labels that each got.

#393 Remove release drafter due to enabled cd
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#394 chore: Remove `developers` tag from pom.xml
  pom.xml
Labels: chore

#396 Do not execute cache step body callback on CPS VM thread
  project-env.toml
  src/main/java/jenkins/plugins/jobcacher/pipeline/CacheStepExecution.java
Labels: bug

#399 feat(java): Require Jenkins core 2.479.3 and Java 17.
  pom.xml
  src/main/java/jenkins/plugins/itemstorage/GlobalItemStorage.java
  src/main/java/jenkins/plugins/itemstorage/ObjectPath.java
  src/main/java/jenkins/plugins/itemstorage/local/LocalObjectPath.java
  src/main/java/jenkins/plugins/itemstorage/s3/S3ObjectPath.java
  src/main/java/jenkins/plugins/jobcacher/ArbitraryFileCache.java
  src/main/java/jenkins/plugins/jobcacher/Cache.java
  src/main/java/jenkins/plugins/jobcacher/CacheProjectAction.java
Labels: dependencies, developer
